name: observing
description: A MobX + Provider convenience package
version: 0.0.1
homepage: https://github.com/nicholasspencer/observing

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.0
  flutter_mobx: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  mobx: ^1.0.0
  mobx_codegen: ^1.0.0
  pedantic:
